Workday/canvas-tokens

jest.config.ts
package.json
packages/canvas-tokens/utils/formatters/helpers/formattedObjectValue.ts
packages/canvas-tokens/utils/setConfig.ts
packages/canvas-tokens/utils/spec/transforms.spec.ts
packages/canvas-tokens/utils/tokenStudioParser.ts
packages/canvas-tokens/utils/transformers/transformNameToCamelCase.ts

n/a
There were a handful of eslint and test errors that were failing. This PR resolves those issues.
`packages/canvas-tokens/utils/spec/transforms.spec.ts`
run `npm test` and `npm run lint`

chore: Fix lint errors and tests

---

.github/workflows/pull-request.yml
.gitignore
package.json

#5 
This PR adds a GitHub action to lint, type check, and test the branch.
.github/workflows/pull-request.yml
I tested this action in [a PR on my fork](https://github.com/alanbsmith/canvas-tokens/pull/1).

chore: Add pull request action

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
package-lock.json
package.json

Resolves #3
This PR adds the initial changeset setup. It also cleans up a few other minor file issues.
`package.json`
`npx changeset`

chore: Add changesets

---

.github/workflows/enable-automerge.yml

Resolves #16 
Adds enable automerge workflow

feat: Add automerge workflow

---

.github/workflows/release-web.yml
.prettierignore
scripts/utils/update-changelog.ts

Resolve #14 
Contains Release Action to force release job for `canvas-tokens-web` package.

feat(web): Web Release Action

---

.github/workflows/release-web.yml

fix(web): Fix npm publish step

---

.github/workflows/release-web.yml
.prettierignore
scripts/utils/update-changelog.ts

Resolves #14 
Contains Release Action to force release job for `canvas-tokens-web` package.

feat(web): Release action

---

.changeset/config.json
.github/workflows/release-web.yml
.prettierignore
package.json
scripts/utils/update-changelog.ts

Resolve #14 
Contains Release Action to force release job for `canvas-tokens-web` package.

feat(web): Add release action

---

.github/workflows/release-web.yml

Resolve #14 
Contains Release Action updates to split release and publish jobs

fix(web): Update release job

---

.github/workflows/release-web.yml

Resolve #34
Adds GH release step to release action

feat(web): Add GH release step to release action

---

.github/workflows/release-web.yml

Resolve #36
Remove publish step and auto release on push to `main`

chore(web): Remove publish on push

---

.github/workflows/merge.yml
.github/workflows/pull-request.yml
scripts/tokens-config.ts
scripts/utils/api-client.ts
scripts/utils/file-content.ts
scripts/utils/pull-request.ts

E.g. Fixes #51
Made a few fixes and updates to the sync utils.

fix: Fix token-sync utils

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Resolves #48
- Adds step-by-step instructions for contributions
- Updates the pull request template to match our automation
Documentation
`CONTRIBUTING.md`

docs: Update Contributing guidelines

---

scripts/utils/update-changelog.ts

N/A
Syncs Canvas Tokens with Tokens Studio
Infrastructure

feat: Update changelog generator

---

.github/workflows/forward-merge.yml
scripts/utils/forward-merge.js

Resolves #65 
In this PR it adds forward merge action to sync `main` and `prerelease/major` branches
Infrastructure

feat: Add forward-merge action

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/forward-merge.yml

Resolves #73
Added a condition to skip not release commits to be forward merged
Infrastructure

feat: Add skip condition to forward merge

---

.github/workflows/release-web.yml

Update release automation to publish web package from GitHub action.
Infrastructure
---

chore: Update Release Automation

---

packages/canvas-tokens/tokens/web/sys.json
packages/canvas-tokens/utils/tokenStudioParser.ts

Resolves: #87
This PR adds system color and breakpoint tokens.
Tokens
This PR adds system color tokens: `bg`, `text`, `icon`, `fg`, `border`, `shadow`, and `static`.
It also adds tokens for viewport breakpoints: `zero`, `s`, `m`, `l`, and `xl`.
---

feat: Add system color tokens

---

packages/canvas-tokens-web/CHANGELOG.md
packages/canvas-tokens-web/package.json
packages/canvas-tokens/tokens/web/sys.json
yarn.lock

Resolves #99
Add and update missing system color tokens
Tokens
Background Color Updates
- Update system.color.bg.muted.soft (licorice.200)
- Add system.color.bg.muted.softer (licorice.100)
- Add system.color.bg.alt.softer (soap.100)
Border Color Updates
- Add system.color.border.input.inverse (soap.300)
Foreground Color Updates
- Add system.color.fg.muted.soft (licorice.200)
Static Color Updates
- Add system.color.static.gold.stronger (toastedMarshmallow.600)
Text Color Updates
- Add system.color.text.primary.stronger (blueberry.600)
---

feat: Add missing system color tokens

---

packages/canvas-tokens-docs/components/ColorGrid.tsx
packages/canvas-tokens-docs/stories/system/ColorBackground.stories.mdx
packages/canvas-tokens-docs/stories/system/ColorBorder.stories.mdx
packages/canvas-tokens-docs/stories/system/ColorForeground.stories.mdx
packages/canvas-tokens-docs/stories/system/ColorIcon.stories.mdx
packages/canvas-tokens-docs/stories/system/ColorStatic.stories.mdx
packages/canvas-tokens-docs/stories/system/ColorText.stories.mdx
packages/canvas-tokens-docs/stories/system/examples/Color/Background.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Border.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Foreground.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Icon.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Static.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Text.tsx

Resolves #101
This PR adds initial system color token docs
Documentation
---

docs: Add system color stories [skip release]

---

.github/workflows/project-automations.yml

Adding the workflow for the Canvas Project Board to automatically add issues to the project
Infrastructure

chore: Add workflow for project board

---

README.md

Resolves #122
This PR adds a version support SLA to the README
Documentation
`README.md`

docs: Add Version Support SLA

---

packages/canvas-tokens-docs/components/ColorGrid.tsx
packages/canvas-tokens-docs/components/TokenGrid/index.css
packages/canvas-tokens-docs/stories/base/Base.stories.mdx
packages/canvas-tokens-docs/stories/base/examples/BaseUnit.tsx
packages/canvas-tokens-docs/stories/base/examples/Color.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Background.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Border.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Foreground.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Icon.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Static.tsx
packages/canvas-tokens-docs/stories/system/examples/Color/Text.tsx
packages/canvas-tokens-docs/stories/system/examples/Shape.tsx
packages/canvas-tokens-docs/stories/system/examples/Space.tsx
packages/canvas-tokens-docs/stories/system/visual-testing/Color.stories.tsx
packages/canvas-tokens/build.ts
packages/canvas-tokens/tokens/base.json
packages/canvas-tokens/tokens/web/brand.json
packages/canvas-tokens/tokens/web/sys.json
packages/canvas-tokens/utils/filters/index.ts
packages/canvas-tokens/utils/formatters/formatTypes.ts
packages/canvas-tokens/utils/transformers/index.ts

Resolves #153 
Added new color tokens 
Tokens
Alpha version of new color tokens.

chore: Sync tokens from canvas-tokens-studio

---

packages/canvas-tokens/build.ts

Filter action tokens from css.
Web Tokens
---

fix: Filter action tokens from css files

---

packages/canvas-tokens-docs/.storybook/global.css
packages/canvas-tokens-docs/components/DownloadLLMFile/index.css
packages/canvas-tokens-docs/components/DownloadLLMFile/index.tsx
packages/canvas-tokens-docs/components/StatusIndicator/index.css
packages/canvas-tokens-docs/components/StatusIndicator/index.tsx
packages/canvas-tokens-docs/llm-txt/llm-token-migration.txt
packages/canvas-tokens-docs/stories/migration/v3MigrationOverview.stories.mdx

Resolves #186 
Added LLM section to guide
Documentation
---

docs: Add llm txt file to overview page

---

packages/canvas-tokens-docs/llm-txt/llm-token-migration-3.0.0.txt
packages/canvas-tokens-docs/stories/base/examples/data/deprecatedMapping.ts

Updates docs
Documentation
---

docs: Fix inverse token
